project:
  type: website
  output-dir: docs
  render: 
  - index.qmd
  - installation.qmd
  - languages-as-formal-objects/index.qmd
  - languages-as-formal-objects/index.qmd
  - languages-as-formal-objects/sets.ipynb
  - languages-as-formal-objects/multisets.ipynb
  - languages-as-formal-objects/tuples.ipynb
  - languages-as-formal-objects/cardinality.ipynb
  - languages-as-formal-objects/set-relations.ipynb
  - languages-as-formal-objects/power-sets.ipynb
  - languages-as-formal-objects/products.ipynb
  - languages-as-formal-objects/relations-and-functions.ipynb
  - languages-as-formal-objects/sequences.ipynb
  - languages-as-formal-objects/strings.ipynb
  - languages-as-formal-objects/languages.ipynb
  - grammars-as-languages/index.qmd
  - grammars-as-languages/defining-regular-expressions.ipynb
  - grammars-as-languages/evaluating-regular-expressions.ipynb
  - grammars-as-languages/loading-a-lexicon.ipynb
  - grammars-as-languages/basic-matching.ipynb
  - grammars-as-languages/implementing-the-regular-operations.ipynb
  - grammars-as-languages/wild-cards-and-character-ranges.ipynb
  - grammars-as-languages/quantifiers.ipynb
  - grammars-as-languages/groups-and-greediness.ipynb
  - uncertainty-about-languages/index.qmd
  - uncertainty-about-languages/what-is-a-probability.ipynb
  - uncertainty-about-languages/how-we-model-possibilities.ipynb
  - uncertainty-about-languages/what-it-means-to-measure-a-possibility.ipynb
  - uncertainty-about-languages/some-useful-definitions.ipynb
  - uncertainty-about-languages/random-variables-and-probability-distributions/index.qmd
  - uncertainty-about-languages/random-variables-and-probability-distributions/random-variables.qmd
  - uncertainty-about-languages/random-variables-and-probability-distributions/probability-distributions.ipynb
  - uncertainty-about-languages/some-more-useful-definitions.qmd
  - uncertainty-about-languages/statistical-inference.qmd
  - languages-in-terms-of-strings/index.qmd
  - languages-in-terms-of-strings/distance-in-the-abstract.qmd
  - languages-in-terms-of-strings/levenshtein-distance.qmd
  - working-with-annotated-corpora/index.qmd
  - working-with-annotated-corpora/trees.ipynb
  - working-with-annotated-corpora/containment-tests.ipynb
  - working-with-annotated-corpora/indexation.ipynb
  - working-with-annotated-corpora/finding-data-with-tree-pattern-matching.ipynb
  - working-with-annotated-corpora/building-a-corpus-reader.ipynb
  - phonological-patterns/index.qmd
  - phonological-patterns/generation.qmd
  - phonological-patterns/the-generativist-conceit.qmd
  - phonological-patterns/formal-definition/index.qmd
  - phonological-patterns/formal-definition/the-regular-operations.qmd
  - phonological-patterns/formal-definition/two-equivalent-definitions.qmd
  - phonological-patterns/formal-definition/translating-between-formalisms.qmd
  - phonological-patterns/formal-definition/beyond-the-regular-operations.qmd
  - phonological-patterns/generative-capacity/index.qmd
  - phonological-patterns/generative-capacity/pumping-lemma.qmd
  - phonological-patterns/phonological-rules-as-fsas/index.qmd
  - phonological-patterns/phonological-rules-as-fsas/finite-state-transducers.qmd
  - phonological-patterns/phonological-rules-as-fsas/fst-operations.qmd
  - phonological-patterns/phonological-rules-as-fsas/parsing-and-transduction.qmd
  - phonological-patterns/phonological-rules-as-fsas/rule-formalism.qmd
  - phonological-patterns/recognition-and-parsing/index.qmd
  - phonological-patterns/recognition-and-parsing/recognition.qmd
  - phonological-patterns/recognition-and-parsing/parsing.qmd
  - morphological-patterns/index.qmd
  - morphological-patterns/operations.qmd
  - morphological-patterns/normal-forms.qmd
  - morphological-patterns/cky-parsing.qmd
  - morphological-patterns/earley-parsing.qmd
  - morphological-patterns/probabilistic-context-free-grammars.qmd
  - syntactic-patterns/index.qmd
  - analysis-as-deduction/index.qmd
  - assignments/assignments-1-and-2.ipynb
  - assignments/assignments-3-and-4.ipynb
  - assignments/assignments-5-and-6.ipynb
  - assignments/assignments-7-and-8.ipynb
  - assignments/assignments-9-and-10.ipynb
  - assignments/final-project.ipynb

website:
  title: "Introduction to Computational Linguistics"
  page-navigation: true
  sidebar:
    style: docked
    search: true
    contents:
      - index.qmd
      - installation.qmd
      - section: "Languages as formal objects"
        contents:
        - languages-as-formal-objects/index.qmd
        - languages-as-formal-objects/sets.ipynb
        - languages-as-formal-objects/multisets.ipynb
        - languages-as-formal-objects/tuples.ipynb
        - languages-as-formal-objects/cardinality.ipynb
        - languages-as-formal-objects/set-relations.ipynb
        - languages-as-formal-objects/power-sets.ipynb
        - languages-as-formal-objects/products.ipynb
        - languages-as-formal-objects/relations-and-functions.ipynb
        - languages-as-formal-objects/sequences.ipynb
        - languages-as-formal-objects/strings.ipynb
        - languages-as-formal-objects/languages.ipynb
      - section: "Grammars as languages"
        contents:
        - grammars-as-languages/index.qmd
        - grammars-as-languages/defining-regular-expressions.ipynb
        - grammars-as-languages/evaluating-regular-expressions.ipynb
        - grammars-as-languages/loading-a-lexicon.ipynb
        - grammars-as-languages/basic-matching.ipynb
        - grammars-as-languages/implementing-the-regular-operations.ipynb
        - grammars-as-languages/wild-cards-and-character-ranges.ipynb
        - grammars-as-languages/quantifiers.ipynb
        - grammars-as-languages/groups-and-greediness.ipynb
      - section: "Uncertainty about Languages"
        contents:
        - uncertainty-about-languages/index.qmd
        - uncertainty-about-languages/what-is-a-probability.ipynb
        - uncertainty-about-languages/how-we-model-possibilities.ipynb
        - uncertainty-about-languages/what-it-means-to-measure-a-possibility.ipynb
        - uncertainty-about-languages/some-useful-definitions.ipynb
        - section: "Random Variables and Probability Distributions"
          contents:
          - uncertainty-about-languages/random-variables-and-probability-distributions/index.qmd
          - uncertainty-about-languages/random-variables-and-probability-distributions/random-variables.qmd
          - uncertainty-about-languages/random-variables-and-probability-distributions/probability-distributions.ipynb
        - uncertainty-about-languages/some-more-useful-definitions.qmd
        - uncertainty-about-languages/statistical-inference.qmd
      - section: "Languages in terms of Strings"
        contents:
        - languages-in-terms-of-strings/index.qmd
        - languages-in-terms-of-strings/distance-in-the-abstract.qmd
        - languages-in-terms-of-strings/levenshtein-distance.qmd
      - section: "Working with Annotated Corpora"
        contents:
        - working-with-annotated-corpora/index.qmd
        - working-with-annotated-corpora/trees.ipynb
        - working-with-annotated-corpora/containment-tests.ipynb
        - working-with-annotated-corpora/indexation.ipynb
        - working-with-annotated-corpora/finding-data-with-tree-pattern-matching.ipynb
        - working-with-annotated-corpora/building-a-corpus-reader.ipynb
      - section: "The nature of phonological patterns"
        contents:
        - phonological-patterns/index.qmd
        - phonological-patterns/generation.qmd
        - phonological-patterns/the-generativist-conceit.qmd
        - section: "Formal definition"
          contents:
          - phonological-patterns/formal-definition/index.qmd
          - phonological-patterns/formal-definition/two-equivalent-definitions.qmd
          - phonological-patterns/formal-definition/the-regular-operations.qmd
          - phonological-patterns/formal-definition/translating-between-formalisms.qmd
          - phonological-patterns/formal-definition/beyond-the-regular-operations.qmd
        - section: "Recognition and parsing"
          contents:
          - phonological-patterns/recognition-and-parsing/index.qmd
          - phonological-patterns/recognition-and-parsing/recognition.qmd
          - phonological-patterns/recognition-and-parsing/parsing.qmd
        - section: "Phonological rules as FSAs"
          contents:
          - phonological-patterns/phonological-rules-as-fsas/index.qmd
          - phonological-patterns/phonological-rules-as-fsas/finite-state-transducers.qmd
          - phonological-patterns/phonological-rules-as-fsas/fst-operations.qmd
          - phonological-patterns/phonological-rules-as-fsas/parsing-and-transduction.qmd
          - phonological-patterns/phonological-rules-as-fsas/rule-formalism.qmd
        - section: "Generative capacity"
          contents:
          - phonological-patterns/generative-capacity/index.qmd
          - phonological-patterns/generative-capacity/pumping-lemma.qmd
      - section: "The nature of morphological patterns"
        contents:
        - morphological-patterns/index.qmd
        - morphological-patterns/operations.qmd
        - morphological-patterns/normal-forms.qmd
        - morphological-patterns/cky-parsing.qmd
        - morphological-patterns/earley-parsing.qmd
        - morphological-patterns/probabilistic-context-free-grammars.qmd
      - section: "Analysis as deduction"
        contents:
        - analysis-as-deduction/index.qmd
      - section: "The nature of syntactic patterns"
        contents:
        - syntactic-patterns/index.qmd
      - section: "Assignments"
        contents:
        - assignments/assignments-1-and-2.ipynb
        - assignments/assignments-3-and-4.ipynb
        - assignments/assignments-5-and-6.ipynb
        - assignments/assignments-7-and-8.ipynb
        - assignments/assignments-9-and-10.ipynb
        - assignments/final-project.ipynb

format:
  html:
    theme: lux
    highlight-style: oblivion
    css: styles.css
    toc: true
    code-tools: true

filters:
  - include-code-files
  - line-highlight

comments:
  giscus: 
    repo: aaronstevenwhite/intro-to-cl



