project:
  type: website
  output-dir: docs
  render: 
    - index.qmd
    - installation.qmd
    - formal-and-practical-preliminaries/index.qmd
    - formal-and-practical-preliminaries/elementary-mathematical-concepts/index.qmd
    - formal-and-practical-preliminaries/elementary-mathematical-concepts/sets.ipynb
    - formal-and-practical-preliminaries/elementary-mathematical-concepts/multisets.ipynb
    - formal-and-practical-preliminaries/elementary-mathematical-concepts/cardinality.ipynb
    - formal-and-practical-preliminaries/elementary-mathematical-concepts/set-relations.ipynb
    - formal-and-practical-preliminaries/elementary-mathematical-concepts/power-sets.ipynb
    - formal-and-practical-preliminaries/elementary-mathematical-concepts/products.ipynb
    - formal-and-practical-preliminaries/elementary-mathematical-concepts/relations-and-functions.ipynb
    - formal-and-practical-preliminaries/elementary-mathematical-concepts/sequences.ipynb
    - formal-and-practical-preliminaries/elementary-mathematical-concepts/strings.ipynb
    - formal-and-practical-preliminaries/elementary-mathematical-concepts/languages.ipynb
    - formal-and-practical-preliminaries/regular-expressions/index.qmd
    - formal-and-practical-preliminaries/regular-expressions/formal-definition.ipynb
    - formal-and-practical-preliminaries/regular-expressions/using-regular-expressions.qmd
    - formal-and-practical-preliminaries/regular-expressions/loading-a-lexicon.ipynb
    - formal-and-practical-preliminaries/regular-expressions/basic-matching.ipynb
    - formal-and-practical-preliminaries/regular-expressions/implementing-the-regular-operations.ipynb
    - formal-and-practical-preliminaries/regular-expressions/wild-cards-and-character-ranges.ipynb
    - formal-and-practical-preliminaries/regular-expressions/quantifiers.ipynb
    - formal-and-practical-preliminaries/regular-expressions/groups-and-greediness.ipynb
    - formal-and-practical-preliminaries/text-normalization/index.qmd
    - formal-and-practical-preliminaries/text-normalization/tokenization.ipynb
    - formal-and-practical-preliminaries/text-normalization/sentence-separation.ipynb
    - formal-and-practical-preliminaries/text-normalization/lemmatization.ipynb
    - formal-and-practical-preliminaries/working-with-annotated-corpora/index.qmd
    - formal-and-practical-preliminaries/edit-distance-and-string-alignment/index.qmd
    - formal-and-practical-preliminaries/text-normalization/index.qmd
    - formal-and-practical-preliminaries/edit-distance-and-string-alignment/index.qmd
    - formal-and-practical-preliminaries/edit-distance-and-string-alignment/distance-in-the-abstract.qmd
    - formal-and-practical-preliminaries/edit-distance-and-string-alignment/levenshtein-distance.qmd
    - formal-and-practical-preliminaries/working-with-annotated-corpora/index.qmd
    - formal-and-practical-preliminaries/working-with-annotated-corpora/trees.ipynb
    - formal-and-practical-preliminaries/working-with-annotated-corpora/containment-tests.ipynb
    - formal-and-practical-preliminaries/working-with-annotated-corpora/indexation.ipynb
    - formal-and-practical-preliminaries/working-with-annotated-corpora/finding-data-with-tree-pattern-matching.ipynb
    - formal-and-practical-preliminaries/working-with-annotated-corpora/building-a-corpus-reader.ipynb
    - finite-state-models/index.qmd
    - finite-state-models/levels-of-abstraction.qmd
    - finite-state-models/generation.qmd
    - finite-state-models/the-generativist-conceit.qmd
    - finite-state-models/formal-definition/index.qmd
    - finite-state-models/formal-definition/two-equivalent-definitions.qmd
    - finite-state-models/formal-definition/the-regular-operations.qmd
    - finite-state-models/generative-capacity/index.qmd
    - finite-state-models/recognition-and-parsing/index.qmd
    - finite-state-models/phonological-rules-as-fsas/index.qmd
    - context-free-models/index.qmd
    - mildly-context-sensitive-models/index.qmd
    - assignments/assignments-1-and-2.ipynb
    - assignments/assignments-3-and-4.ipynb


website:
  title: "Introduction to Computational Linguistics"
  page-navigation: true
  sidebar:
    style: docked
    search: true
    contents:
      - index.qmd
      - installation.qmd
      - section: "Formal and Practical Preliminaries"
        contents:
          - formal-and-practical-preliminaries/index.qmd
          - section: "Elementary Mathematical Concepts"
            contents:
              - formal-and-practical-preliminaries/elementary-mathematical-concepts/index.qmd
              - formal-and-practical-preliminaries/elementary-mathematical-concepts/sets.ipynb
              - formal-and-practical-preliminaries/elementary-mathematical-concepts/multisets.ipynb
              - formal-and-practical-preliminaries/elementary-mathematical-concepts/cardinality.ipynb
              - formal-and-practical-preliminaries/elementary-mathematical-concepts/set-relations.ipynb
              - formal-and-practical-preliminaries/elementary-mathematical-concepts/power-sets.ipynb
              - formal-and-practical-preliminaries/elementary-mathematical-concepts/products.ipynb
              - formal-and-practical-preliminaries/elementary-mathematical-concepts/relations-and-functions.ipynb
              - formal-and-practical-preliminaries/elementary-mathematical-concepts/sequences.ipynb
              - formal-and-practical-preliminaries/elementary-mathematical-concepts/strings.ipynb
              - formal-and-practical-preliminaries/elementary-mathematical-concepts/languages.ipynb
          - section: "Regular Expressions"
            contents:
              - formal-and-practical-preliminaries/regular-expressions/index.qmd
              - formal-and-practical-preliminaries/regular-expressions/formal-definition.ipynb
              - formal-and-practical-preliminaries/regular-expressions/loading-a-lexicon.ipynb
              - formal-and-practical-preliminaries/regular-expressions/basic-matching.ipynb
              - formal-and-practical-preliminaries/regular-expressions/implementing-the-regular-operations.ipynb
              - formal-and-practical-preliminaries/regular-expressions/wild-cards-and-character-ranges.ipynb
              - formal-and-practical-preliminaries/regular-expressions/quantifiers.ipynb
              - formal-and-practical-preliminaries/regular-expressions/groups-and-greediness.ipynb
          - section: "Text Normalization"
            contents:
              - formal-and-practical-preliminaries/text-normalization/index.qmd
              - formal-and-practical-preliminaries/text-normalization/tokenization.ipynb
              - formal-and-practical-preliminaries/text-normalization/sentence-separation.ipynb
              - formal-and-practical-preliminaries/text-normalization/lemmatization.ipynb
          - section: "Edit Distance and String Alignment"
            contents:
              - formal-and-practical-preliminaries/edit-distance-and-string-alignment/index.qmd
              - formal-and-practical-preliminaries/edit-distance-and-string-alignment/distance-in-the-abstract.qmd
              - formal-and-practical-preliminaries/edit-distance-and-string-alignment/levenshtein-distance.qmd
          - section: "Working with Annotated Corpora"
            contents:
              - formal-and-practical-preliminaries/working-with-annotated-corpora/index.qmd
              - formal-and-practical-preliminaries/working-with-annotated-corpora/trees.ipynb
              - formal-and-practical-preliminaries/working-with-annotated-corpora/containment-tests.ipynb
              - formal-and-practical-preliminaries/working-with-annotated-corpora/indexation.ipynb
              - formal-and-practical-preliminaries/working-with-annotated-corpora/finding-data-with-tree-pattern-matching.ipynb
              - formal-and-practical-preliminaries/working-with-annotated-corpora/building-a-corpus-reader.ipynb
      - section: "Finite State Models"
        contents:
          - finite-state-models/index.qmd
          - finite-state-models/levels-of-abstraction.qmd
          - finite-state-models/generation.qmd
          - finite-state-models/the-generativist-conceit.qmd
          - section: "Formal Definition"
            contents:
              - finite-state-models/formal-definition/index.qmd
              - finite-state-models/formal-definition/two-equivalent-definitions.qmd
              - finite-state-models/formal-definition/the-regular-operations.qmd
          - section: "Generative Capacity"
            contents:
              - finite-state-models/generative-capacity/index.qmd
          - section: "Recognition and Parsing"
            contents:
              - finite-state-models/recognition-and-parsing/index.qmd
          - section: "Phonological Rules as FSAs"
            contents:
              - finite-state-models/phonological-rules-as-fsas/index.qmd
      - section: "Context Free Models"
        contents:
          - context-free-models/index.qmd
      - section: "Mildly Context Sensitive Models"
        contents:
          - mildly-context-sensitive-models/index.qmd
      - section: "Assignments"
        contents:
          - assignments/assignments-1-and-2.ipynb
          - assignments/assignments-3-and-4.ipynb

format:
  html:
    theme: lux
    highlight-style: oblivion
    css: styles.css
    toc: true
    code-tools: true

filters:
  - include-code-files
  - line-highlight

comments:
  giscus: 
    repo: aaronstevenwhite/intro-to-cl



