---
title: What is a probability?
bibliography: ../references.bib
jupyter: python3
---

A probability is a measurement of a possibility (relative to a range of possibilities). Probability theory is a way of formalizing this idea. The most common such formalization–the [Kolmogorov axioms](https://en.wikipedia.org/wiki/Probability_axioms)–can be thought of as defining: (i) what it means to be a possibility; and (ii) what it means to measure a possibility.

What it means for a quantity to be a probability is a surprisingly contentious topic. It's an interesting topic–and I encourage you to read about [the various possibilities](https://plato.stanford.edu/entries/probability-interpret/)–but for the purposes of this course, we will tend to think of probabilities as a quantification of a degree of belief–e.g. how strongly ones believe that some speaker uttered a high vowel v. a non-high vowel.  This interpretation is sometimes referred to as the subjective or Bayesian interpretation. We'll flesh this idea out as we move through the course.

