---
title: Groups and Greediness
jupyter: python3
---

One of the major uses for regular expressions is for extracting substrings from a string. This can be done with groups. For instance, suppose I want all of stems that have the morpheme with the form /ʃən/.

```{python}
#| code-fold: true
#| code-summary: Load IPA representation of CMU Pronouncing Dictionary

with open("cmudict-ipa") as f:
    entries: list[tuple[str, str]] = [
        l.strip().split(",") for l in f
    ]
    entries: dict[str, list[str]] = {
        w: ipa.split() for w, ipa in entries
    }
```

```{python}
#| colab: {base_uri: 'https://localhost:8080/'}
#| executionInfo: {elapsed: 4, status: ok, timestamp: 1675099877736, user: {displayName: Aaron Steven White, userId: 06256629009318567325}, user_tz: 300}
#| outputId: 06b7bb47-0dd1-4b3a-b8ad-1a99ca57c056
import re

regex_ʃən = '(.+)ʃən'

n_matches = 0

for w, ipa in entries.items():
    if re.fullmatch(regex_ʃən, "".join(ipa)):
        if n_matches < 30:
            n_matches += 1
            print("".join(ipa), re.findall(regex_ʃən, "".join(ipa)), f"({w})")
        else:
            print("...")
            break
```

This works to some extent, but notice that it will capture cases where /ʃən/ is not a morpheme. For instance, the word *passion* will get matched. It will also return the wrong stem when the morpheme is realized as /eɪʃən/, such as *accreditation*.

```{python}
re.findall(regex_ʃən, "".join(entries["passion"])), re.findall(regex_ʃən, "".join(entries["accreditation"]))
```

To handle the second, we might look for /eɪʃən/ and /ʃən/. We can use the quantifier `?` to say that /eɪ/ is optional. Because it is a digraph, we need to surround it with parentheses. 

```{python}
regex_ʃən = '(.+)(eɪ)?ʃən'

n_matches = 0

for w, ipa in entries.items():
    if re.fullmatch(regex_ʃən, "".join(ipa)):
        if n_matches < 30:
            n_matches += 1
            print("".join(ipa), re.findall(regex_ʃən, "".join(ipa)), f"({w})")
        else:
            print("...")
            break
```

The problem is that this makes Python think we want to capture it. So what we need is a non-capturing group, which we get by putting `?:` after the open parenthesis.

```{python}
regex_ʃən = '(.+)(?:eɪ)?ʃən'

n_matches = 0

for w, ipa in entries.items():
    if re.fullmatch(regex_ʃən, "".join(ipa)):
        if n_matches < 30:
            n_matches += 1
            print("".join(ipa), re.findall(regex_ʃən, "".join(ipa)), f"({w})")
        else:
            print("...")
            break
```

It still seems to be capturing /eɪ/ in *accreditation*. What gives? The reason this is happening is that quantifiers like `+` are *greedy* by default. That means they will match as much as they can. And because /eɪ/ is optional, `(.+)` can match it.

To make sure it doesn't match it if it doesn't need to, we can make the quantifier non-greedy by appending a `?`.

```{python}
regex_ʃən = '(.+?)(?:eɪ)?ʃən'

n_matches = 0

for w, ipa in entries.items():
    if re.fullmatch(regex_ʃən, "".join(ipa)):
        if n_matches < 30:
            n_matches += 1
            print("".join(ipa), re.findall(regex_ʃən, "".join(ipa)), f"({w})")
        else:
            print("...")
            break
```

Okay. So how do we deal with cases where /ʃən/ is not a morpheme? One thing we can do is to look for stems that show up without /ʃən/. This will exclude *passion*, since /pæ/ is not a word.

```{python}
regex_ʃən = '(.+?)(?:eɪ)?ʃən'

n_matches = 0
seen = set()

for w1, ipa1 in entries.items():
    possible_morpheme = re.findall(regex_ʃən, "".join(ipa1))
    if possible_morpheme:
        for w2, ipa2 in entries.items():
            if re.fullmatch(possible_morpheme[0], "".join(ipa2)):
                if n_matches < 20 and "".join(ipa2) not in seen:
                    n_matches += 1
                    seen |= {"".join(ipa2)}
                    print("".join(ipa2), f"({w2})", "+", "ʃən", "=", "".join(ipa1), f"({w1})")
                else:
                    break

    if n_matches >= 20:   
        print("...")
        break
```

An issue here is that /ʃən/ doesn't simply get appended to a stem. There is an additional phonological process that deletes a portion of that stem–e.g. /æbstɹækt/ + /ʃən/ is /æbstɹækʃən/, not  /æbstɹæk**t**ʃən/. So we need to consider cases where a final consonant–usually a `t`–was deleted. But we need to make sure we do so only when the morpheme wasn't realized as /eɪʃən/, so we need to go back to capturing it.

```{python}
#| colab: {base_uri: 'https://localhost:8080/'}
#| executionInfo: {elapsed: 5, status: ok, timestamp: 1675099877737, user: {displayName: Aaron Steven White, userId: 06256629009318567325}, user_tz: 300}
#| outputId: 17b3ba36-8b13-4bf7-edb3-442cdab008cf
regex_ʃən = '(.+?)(eɪ)?ʃən'

n_matches = 0

seen = set()

for w1, ipa1 in entries.items():
    possible_morpheme = re.findall(regex_ʃən, "".join(ipa1))
    if possible_morpheme:
        for w2, ipa2 in entries.items():
            if possible_morpheme[0][1]:
                regex_stem = possible_morpheme[0][0]
            else:
                regex_stem = possible_morpheme[0][0] + "t"
            
            if re.fullmatch(regex_stem, "".join(ipa2)):
                if n_matches < 20 and "".join(ipa2) not in seen:
                    n_matches += 1
                    seen |= {"".join(ipa2)}
                    print("".join(ipa2), f"({w2})", "+", "ʃən", "=", "".join(ipa1), f"({w1})")
                else:
                    break

    if n_matches >= 20:   
        print("...")
        break
```

There's still some wonky stuff in here–e.g. *ancient* coming from *ain't* and *ashen* coming from *at*–but we're getting closer. We can't really deal with cases like *ashen* coming from *at*, but we can deal with *ancient* coming from *ain't*, which reveals a behavior of `re.findall`: it functions like `re.match`, rather than `re.fullmatch`, in that it matches the beginning of a string. If we want it to match the entire string, we have to explicitly specify that in the regular expression. To do this, we can use a `$`, which means "end of string".^[The dual of `$` for the beginning of the string is `^`. Note that this looks like the negation symbol we saw earlier. It is different in that that symbol must be preceded by `[` to be interpreted as negation. Anywhere else `^` means the beginning of a string. That in turn means that putting a bare `^` anywhere besides the beginning of a regular expression is going to result in a regular expression that evaluates to the empty set.] 

```{python}
#| colab: {base_uri: 'https://localhost:8080/'}
#| executionInfo: {elapsed: 4, status: ok, timestamp: 1675103797019, user: {displayName: Aaron Steven White, userId: 06256629009318567325}, user_tz: 300}
#| outputId: 5a2743c7-b97a-465a-b61f-8911d356e624
regex_ʃən = '(.+?)(eɪ)?ʃən$'

n_matches = 0

seen = set()

for w1, ipa1 in entries.items():
    possible_morpheme = re.findall(regex_ʃən, "".join(ipa1))
    if possible_morpheme:
        for w2, ipa2 in entries.items():
            if possible_morpheme[0][1]:
                regex_stem = possible_morpheme[0][0]
            else:
                regex_stem = possible_morpheme[0][0] + "t"
            
            if re.fullmatch(regex_stem, "".join(ipa2)):
                if n_matches < 20 and "".join(ipa2) not in seen:
                    n_matches += 1
                    seen |= {"".join(ipa2)}
                    print("".join(ipa2), f"({w2})", "+", "ʃən", "=", "".join(ipa1), f"({w1})")
                else:
                    break

    if n_matches >= 20:   
        print("...")
        break
```

To get much better than this, we'd need to start matching on the orthographic representation as well–e.g. matching the *ion* at the end of the orthographic representation of the word, thus filtering things like /æt/ + /ʃən/ = /æʃən/. One thing we'll still miss are cases like *adoration*, where there is a vowel quality change (which is consequently why we get *adder* + *ion* = *adoration* currently). To handle those cases, we would need to account for the conditions under which vowel quality changes, which we could do in principle using regular expressions but which I won't do here.

